csk/urls.py
from django.urls import path
from csk.views import *

app_name='csk'

urlpatterns=[
    path('msd/',msd,name='msd'),
]

project20/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb
from india.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
    path('sehwag/',sehwag,name='sehwag'),
]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name='rcb'

urlpatterns=[
    path('virat/',virat,name='virat'),
]

india/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def msd(request):
    return render(request,'msd.html')

india/views.py
from django.shortcuts import render

# Create your views here.
def sehwag(request):
    return render(request,'sehwag.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/msd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> THIS IS MSD PAGE</h1>
        <h1><a href="{% url 'rcb:virat' %}">Go To virat</a></h1>
        <h1><a href="{% url 'sehwag' %}">go to sehwag</a></h1>
    </center>
</body>
</html>

templates/sehwag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS SEHWAG PAGE</h1>
        <h1><a href="{% url 'csk:msd' %}">go to csk</a></h1>
        <h1><a href="{% url 'rcb:virat' %}">go to rcb</a></h1>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   
        <h1>THIS IS VIRAT PAGE</h1>
        <h1><a href="{% url 'csk:msd' %}">Go To MSD</a></h1>


   
</body>
</html>